version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: .
      dockerfile: ./app/api/Dockerfile
    container_name: square-kart-api
    ports:
      - 4000:4000
    environment:
      - ENV=dev
      - CORS_ORIGIN=http://localhost:3000
      - PORT=4000
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=test
      - DB_PASS=test
      - EXPRESS_SESSION_SECRET=secure

  web:
    build:
      context: .
      dockerfile: ./app/web/Dockerfile
    container_name: square-kart-web
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BASE_URL=http://localhost:4000
